services:
  webapp:
    depends_on:
      db:
        condition: service_healthy
    environment:
      - LORC_DB_HOST
      - LORC_DB_PORT
      - LORC_DB_USER
      - LORC_DB_PASS

  db:
    image: postgis/postgis:16-3.4
    container_name: db
    ports:
      - ${LORC_DB_PORT}:5432
    environment:
      POSTGRES_USER: "${LORC_DB_USER}"
      POSTGRES_PASSWORD: "${LORC_DB_PASS}"
      POSTGRES_DB: "liveorc"
    volumes:
      - ${LORC_DB_DIR}:/var/lib/postgresql/data:Z
    restart: unless-stopped
    healthcheck:
      test: pg_isready -U ${LORC_DB_USER} -d liveorc
      interval: 1s
      timeout: 20s
      retries: 10
      start_period: 5s
volumes:
  lorc_data:
