#version: '3'
services:
  webapp:
    depends_on:
      - db:
        condition: service_healthy
  db:
    image: postgis/postgis
    container_name: db
    ports:
      - ${LORC_DB_PORT}:5432
    environment:
      POSTGRES_USER: "${LORC_DB_USER}"
      POSTGRES_PASSWORD: "${LORC_DB_PASSWORD}"
      POSTGRES_DB: "liveorc"
    volumes:
      - ${LORC_DB_DIR}:/var/lib/postgresql/data:Z
    restart: unless-stopped
volumes:
  lorc_data:
