services:
  webapp:
    depends_on:
      - rabbitmq
    environment:
      - LORC_RABBITMQ_HOST
      - LORC_RABBITMQ_PASS
      - LORC_RABBITMQ_USER
  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    hostname: rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: password
    ports:
      - "5672:5672"
      - "15672:15672"
