#version: '3'
services:
  webapp:
    build:
      context: .
      dockerfile: Dockerfile
    image: liveopenrivercam
    container_name: liveorc_webapp
    entrypoint: /bin/bash -c "/liveorc/start.sh"
    restart: unless-stopped
    volumes:
      - .:/liveorc:z
      - ${LORC_STORAGE_DIR}:/liveorc/data/media:z
    environment:
      - DJANGO_DBASE_DIR=/liveorc/data
      - "${LORC_STORAGE_ACCESS}:MINIO_ROOT_USER"
      - "${LORC_STORAGE_SECRET}:MINIO_ROOT_PASSWORD"
      - LORC_PORT
      - LORC_HOST
      - LORC_SECRET_KEY
      - LORC_DEBUG
      - LORC_SSL
    ports:
      - "${LORC_PORT}:8000"
volumes:
  lorc_data:
  lorc_media:
