#version: '3'
services:
  storage:
    image: minio/minio
    ports:
      - 9000:9000
      - 9001:9001
    environment:
      MINIO_ROOT_USER: "${LORC_STORAGE_ACCESS}"
      MINIO_ROOT_PASSWORD: "${LORC_STORAGE_SECRET}"
      MINIO_CONSOLE_PORT: 9001

    volumes:
      - lorc_data:/data
    command: server /data --console-address ":9001"