# This configuration adds support for SSL
version: '2.1'
volumes:
  letsencrypt:
    driver: local
services:
  webapp:
    ports:
      - "${WO_SSL_INSECURE_PORT_REDIRECT}:8080"
    volumes:
      - letsencrypt:/webodm/nginx/letsencrypt
    environment:
      - LORC_SSL
      - LORC_SSL_KEY
