# Generated by Django 5.0.6 on 2024-09-26 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cameraconfig',
            name='version',
            field=models.CharField(blank=True, editable=False, max_length=15, verbose_name='pyORC version compatibility'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='version',
            field=models.CharField(blank=True, editable=False, max_length=15),
        ),
    ]
