# Generated by Django 5.1.1 on 2025-06-30 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_cameraconfig_version_alter_recipe_version'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeseries',
            name='q_raw',
            field=models.FloatField(blank=True, help_text='River flow measured optically', null=True, verbose_name='Raw discharge'),
        ),
        migrations.AddField(
            model_name='timeseries',
            name='v_av',
            field=models.FloatField(blank=True, help_text='Average surface velocity [m/s]', null=True),
        ),
        migrations.AddField(
            model_name='timeseries',
            name='v_bulk',
            field=models.FloatField(blank=True, help_text='Bulk velocity [m/s]', null=True),
        ),
    ]
