# Generated by Django 5.1.1 on 2026-03-27 09:28

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_model_alignment_videoconfig'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='crosssection',
            options={'verbose_name': 'cross section', 'verbose_name_plural': 'cross sections'},
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql='DROP INDEX IF EXISTS api_video_camera__7fea15_idx;',
                    reverse_sql=migrations.RunSQL.noop,
                ),
            ],
            state_operations=[
                migrations.RemoveIndex(
                    model_name='video',
                    name='api_video_camera__7fea15_idx',
                ),
            ],
        ),
        migrations.RenameIndex(
            model_name='video',
            new_name='api_video_video_c_cfa87d_idx',
            old_name='api_video_videoco_4c47d3_idx',
        ),
        migrations.AlterField(
            model_name='cameraconfig',
            name='allowed_dt',
            field=models.DurationField(default=datetime.timedelta(seconds=1800), help_text='Maximum time difference allowed between an associated video time stamp and a time series instance at the associated site [sec]', validators=[django.core.validators.MinValueValidator(datetime.timedelta(0)), django.core.validators.MaxValueValidator(datetime.timedelta(days=1))], verbose_name='Allowed difference in time stamp'),
        ),
        migrations.AlterField(
            model_name='crosssection',
            name='name',
            field=models.CharField(help_text='Recognizable unique name for your cross section', max_length=100),
        ),
    ]
