name: Build and publish Docker image
on:
  push:
    tags:
    - v*
jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        submodules: 'recursive'
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Docker meta
      id: docker_meta
      uses: crazy-max/ghaction-docker-meta@v1
      with:
        images: localdevices/liveorc
        tag-semver: |
          {{version}}
    - name: Build and push the Docker image
      uses: docker/build-push-action@v5
      with:
        file: ./Dockerfile
        platforms: linux/amd64
        push: true
        no-cache: true
        tags: |
          ${{ steps.docker_meta.outputs.tags }}
          localdevices/liveorc:latest
    - name: Image digest
      run: echo ${{ steps.docker_build.outputs.digest }}
      
